### ISSUE TITLE
diffoscope is missing from propagatedBuildInput

### ISSUE THREAD

**Issue by erdnaxe** [Artturin/diffing#1]
It seems that diffing.py tries to call `diffoscope`, but it is missing from the flake. As a temporary hack, I use `nix-shell -p diffoscope` to then run diffing flake.

```
$ nix run ../diffing ".#haskellPackages.safe-exceptions"
['haskellPackages.safe-exceptions']

-----------------------diffing output doc of haskellPackages.safe-exceptions------------------------
normal: /nix/store/5lgnxcs8p182j7k98k0h1vvvix6rd7zk-safe-exceptions-0.1.7.4-doc
strict: /nix/store/nh4r7wfis09hp2kdpxbzpvlzbznnm5il-safe-exceptions-0.1.7.4-doc

Traceback (most recent call last):
  File "/nix/store/ss27janw9d2p8kpk9pq1k8v963bf6a2p-diffing/bin/diffing", line 195, in <module>
    main()
  File "/nix/store/ss27janw9d2p8kpk9pq1k8v963bf6a2p-diffing/bin/diffing", line 189, in main
    subprocess.run(
  File "/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'diffoscope'
```

(thanks for sharing this cool tool!)

**Comment by Artturin** [comment]
Added a substitute for it.
